baseURL = "/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Solaiman Hridoy"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-173154725-1"

[params]
displayMode = "dark"
title = "Solaiman Hridoy"
author = "Solaiman Hridoy"
description = "Life Is Gorgeous."
profilePicture = "images/My-Pic02.png"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/site-feature-image.png"]

footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

code_copy_button = true



## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/solaimanhridoy"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/solaimanhridoy/"

[[params.socialIcons]]
icon = "fa-facebook"
title = "facebook"
url = "https://www.facebook.com/solaimanhrid0y"
weight = 3 

[[params.socialIcons]]
icon = "fa-gmail"
title = "e-mail"
url = "solaimanhridoy@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "বাংলা ব্লগ"
  weight = 400
  identifier = "ব্লগ"
  url = "/bn/"




